# Tutorial for the Data API

This file contains a tutorial for how to read data from the `data` directory.
The functions have **very precise type annotations**, avoiding *many* potential bugs, and improving developer productivity and efficiency.

In [1]:
from data import *
import pandas as pd

## August 2023 Summary Statistics

This parses the `August2023Summary.csv` file.

In [2]:
summary = read_august_2023_summary()
summary[0]["before_sample"] # Modify the "before_sample" to see how well the type annotation works
pd.DataFrame(summary)

,implementation,before_sample,in_sample,post_sample_but_before_pub,post_pub,last_5_years,year_2022
0,Original Paper,0.55,0.67,0.42,0.32,0.36,0.66
1,HoldPer_1,0.53,0.72,0.49,0.32,0.19,0.80
2,HoldPer_3,0.36,0.62,0.40,0.32,0.38,0.75
3,HoldPer_6,0.30,0.56,0.33,0.28,0.33,0.75
4,HoldPer_12,0.24,0.47,0.26,0.23,0.28,0.62
5,ME_gt_NYSE20pct,0.28,0.49,0.26,0.23,0.26,0.76
6,NYSEonly,0.38,0.45,0.21,0.27,0.30,0.75
7,Price_gt_5,0.34,0.55,0.31,0.23,0.25,0.54
8,VWforce,0.45,0.43,0.26,0.16,0.15,0.58
9,Quintiles (cts only),0.43,0.62,0.39,0.29,0.31,0.66
10,QuintilesVW (cts only),0.33,0.40,0.27,0.15,0.13,0.58
11,Deciles (cts only),0.40,0.77,0.49,0.36,0.38,0.80
12,DecilesVW (cts only),0.34,0.52,0.33,0.20,0.23,0.82
13,FF93style,0.12,0.18,0.10,0.04,0.02,0.40
14,PlaceboPortsFull,0.12,0.26,0.36,0.12,0.11,0.24

## Daily Port Summary

This parses the `DailyPortSummary.csv` file.

In [3]:
pd.DataFrame(DailyPortfolios.read_summary())

,implementation,port,n_distinct,mean_nobs_years,mean_rbar_monthly
0,CTS_PREDICTOR_DECILE,port01,179,68.388603,0.684372
1,CTS_PREDICTOR_DECILE,port02,177,67.366893,0.777174
2,CTS_PREDICTOR_DECILE,port03,177,67.761740,0.923449
3,CTS_PREDICTOR_DECILE,port04,177,67.205356,0.981265
4,CTS_PREDICTOR_DECILE,port05,178,66.335573,1.016766
5,CTS_PREDICTOR_DECILE,port06,178,66.412831,1.058475
6,CTS_PREDICTOR_DECILE,port07,178,66.909416,1.091068
7,CTS_PREDICTOR_DECILE,port08,179,67.200715,1.118744
8,CTS_PREDICTOR_DECILE,port09,179,67.690168,1.177964
9,CTS_PREDICTOR_DECILE,port10,179,68.373453,1.201524
10,CTS_PREDICTOR_DECILE,portLS,179,68.372693,0.516094
11,CTS_PREDICTOR_DECILE_VW,port01,179,68.388603,0.692589
12,CTS_PREDICTOR_DECILE_VW,port02,177,67.366893,0.726839
13,CTS_PREDICTOR_DECILE_VW,port03,177,67.761740,0.838557
14,CTS_PREDICTOR_DECILE_VW,port04,177,67.205356,0.881797
15,CTS_PREDICTOR_DECILE_VW,port05,178,66.335236,0.898415
16,CTS_PREDICTOR_DECILE_VW,port06,178,66.412831,0.921563
17,CTS_PREDICTOR_DECILE_VW,port07,178,66.908966,0.954301
18,CTS_PREDICTOR_DECILE_VW,port08,179,67.200715,0.979369
19,CTS_PREDICTOR_DECILE_VW,port09,179,67.689698,1.026677
20,CTS_PREDICTOR_DECILE_VW,port10,179,68.373453,1.033209
21,CTS_PREDICTOR_DECILE_VW,portLS,179,68.372693,0.339462
22,CTS_PREDICTOR_QUINTILE,port01,179,68.372939,0.766432
23,CTS_PREDICTOR_QUINTILE,port02,177,67.981582,0.959619
24,CTS_PREDICTOR_QUINTILE,port03,178,67.158135,1.043798
25,CTS_PREDICTOR_QUINTILE,port04,179,67.682883,1.095863
26,CTS_PREDICTOR_QUINTILE,port05,179,68.362682,1.184911
27,CTS_PREDICTOR_QUINTILE,portLS,179,68.362637,0.418315
28,CTS_PREDICTOR_QUINTILE_VW,port01,179,68.372939,0.751394
29,CTS_PREDICTOR_QUINTILE_VW,port02,177,67.981582,0.867636
30,CTS_PREDICTOR_QUINTILE_VW,port03,178,67.158135,0.916295
31,CTS_PREDICTOR_QUINTILE_VW,port04,179,67.682883,0.952130
32,CTS_PREDICTOR_QUINTILE_VW,port05,179,68.362682,1.017032
33,CTS_PREDICTOR_QUINTILE_VW,portLS,179,68.362637,0.265466
34,PREDICTOR,port01,212,67.904302,0.731212
35,PREDICTOR,port02,211,67.949991,0.912300
36,PREDICTOR,port03,184,67.227522,1.007399
37,PREDICTOR,port04,178,67.329798,1.057565
38,PREDICTOR,port05,175,68.270789,1.118886
39,PREDICTOR,port06,64,69.312750,1.087659
40,PREDICTOR,port07,62,69.698903,1.097108
41,PREDICTOR,port08,62,69.681935,1.150397
42,PREDICTOR,port09,62,70.076581,1.168108
43,PREDICTOR,port10,62,70.333871,1.231312
44,PREDICTOR,portLS,212,67.598604,0.452026
45,PREDICTOR_VM,port01,212,67.903849,0.734253
46,PREDICTOR_VM,port02,211,67.949991,0.831679
47,PREDICTOR_VM,port03,184,67.227522,0.899556
48,PREDICTOR_VM,port04,178,67.329798,0.940395
49,PREDICTOR_VM,port05,175,68.270446,0.976703
50,PREDICTOR_VM,port06,64,69.312750,0.922595
51,PREDICTOR_VM,port07,62,69.698903,0.929642
52,PREDICTOR_VM,port08,62,69.681935,0.987928
53,PREDICTOR_VM,port09,62,70.076581,0.993589
54,PREDICTOR_VM,port10,62,70.333871,1.040709
55,PREDICTOR_VM,portLS,212,67.598151,0.286185

## Signal Doc

This parses the `SignalDoc.csv` file.

In [4]:
pd.DataFrame(read_signal_doc())

,acronym,cat_signal,op_predictability,signal_rep_quality,authors,year,long_description,journal,cat_form,cat_data,...,return_val,t_stat,stock_weight,ls_quantile,quantile_filter,portfolio_period,start_month,applied_filter,notes,detailed_definition
0,AbnormalAccruals,PREDICTOR,CLEAR,FAIR,Xie,2001,Abnormal Accruals,AR,CONTINUOUS,ACCOUNTING,...,0.916667,8.43,EW,ONE_TENTH,None,ANNUALLY,JUNE,None,OP is aggressive and lags accounting data by o...,Define Accruals as net income (ib) minus opera...
1,Accruals,PREDICTOR,CLEAR,GOOD,Sloan,1996,Accruals,AR,CONTINUOUS,ACCOUNTING,...,0.866667,4.71,EW,ONE_TENTH,None,ANNUALLY,JUNE,abs(prc)>5,Table 6 year t+1 hedge. Only size adjusted an...,Annual change in current total assets (act) mi...
2,AccrualsBM,PREDICTOR,CLEAR,GOOD,Bartov and Kim,2004,Book-to-market and accruals,RFQA,DISCRETE,ACCOUNTING,...,0.206000,5.50,EW,TWO_TENTHS,None,ANNUALLY,JUNE,None,None,Binary variable equal to 1 if stock is in the ...
3,Activism1,PREDICTOR,CLEAR,GOOD,Cremers and Nair,2005,Takeover vulnerability,JF,CONTINUOUS,THIRTEEN_F,...,0.902500,3.13,VW,ONE_QUARTER,None,MONTHLY,JUNE,None,works a bit better EW in Tab 3,24 minus Governance Index (G). Set to missing ...
4,AM,PREDICTOR,CLEAR,GOOD,Fama and French,1992,Total assets to market,JF,CONTINUOUS,ACCOUNTING,...,NaN,5.69,EW,None,None,ANNUALLY,JUNE,None,None,Total assets (at) divided by market value of e...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326,SP_q,PLACEBO,INDIRECT,None,"Barbee, Mukherji and Raines",1996,Sales-to-price quarterly,FAJ,CONTINUOUS,ACCOUNTING,...,NaN,NaN,None,None,None,None,None,None,None,Ratio of annual sales (sale) to market value o...
327,tang_q,PLACEBO,INDIRECT,None,Hahn and Lee,2009,Tangibility quarterly,JF,CONTINUOUS,ACCOUNTING,...,NaN,NaN,None,None,None,None,None,None,None,Cash and short-term investments (che) plus .71...
328,Tax_q,PLACEBO,INDIRECT,None,Lev and Nissim,2004,Taxable income to income (qtrly),AR,CONTINUOUS,ACCOUNTING,...,NaN,NaN,None,None,None,None,None,None,None,Ratio of Taxes paid and tax share of net incom...
329,WW_Q,PLACEBO,INDIRECT,None,Whited and Wu,2006,Whited-Wu index,RFS,CONTINUOUS,ACCOUNTING,...,NaN,NaN,None,None,None,None,None,None,"Insignificant in original paper,",Group data by 3 digit SIC code and month to co...
330,ZScore_q,PLACEBO,INDIRECT,None,Dichev,1998,Altman Z-Score quarterly,JFE,CONTINUOUS,ACCOUNTING,...,NaN,NaN,None,None,None,None,None,None,None,1.2*(current assets (act) - current liabilitie...

## Predictor

This parses a given predictor, given its short name.

In [5]:
values, ports = DailyPortfolios.read_predictor("BidAskSpread", vw=False)
print(ports)
pd.DataFrame(values)

('port01', 'port02', 'port03', 'port04', 'port05', 'port06', 'portLS')

,date,port01,port02,port03,port04,port05,port06,port07,port08,port09,port10,portLS
0,1926-02-01,-0.174025,-0.354044,-0.443207,-0.368607,-0.545103,0.348814,None,None,None,None,0.522839
1,1926-02-02,0.529962,0.606180,0.612349,0.544363,0.402014,0.510969,None,None,None,None,-0.018993
2,1926-02-03,0.602922,0.439322,0.487145,0.350119,0.830027,1.000290,None,None,None,None,0.397368
3,1926-02-04,0.480899,0.315830,0.618086,0.682094,0.612923,0.112668,None,None,None,None,-0.368231
4,1926-02-05,0.073132,-0.163043,-0.051685,0.215276,0.220188,0.867627,None,None,None,None,0.794495
...,...,...,...,...,...,...,...,...,...,...,...,...
25518,2022-12-23,0.111071,0.325080,0.428410,0.615383,0.251195,-0.289216,None,None,None,None,-0.400287
25519,2022-12-27,-0.048859,-0.044397,-0.074606,-0.128443,-1.078780,-2.838162,None,None,None,None,-2.789303
25520,2022-12-28,-0.418795,-0.913687,-1.098363,-1.338935,-1.248627,-1.044593,None,None,None,None,-0.625797
25521,2022-12-29,0.590091,1.310446,1.417995,1.685517,2.933759,3.909154,None,None,None,None,3.319063
25522,2022-12-30,-0.204003,-0.379983,-0.253058,-0.266297,0.500299,2.147605,None,None,None,None,2.351608

In [6]:
values, ports = DailyPortfolios.read_predictor("BidAskSpread", vw=True)
print(ports)
pd.DataFrame(values)

('port01', 'port02', 'port03', 'port04', 'port05', 'port06', 'portLS')

,date,port01,port02,port03,port04,port05,port06,port07,port08,port09,port10,portLS
0,1926-02-01,-0.132456,-0.473825,-0.586829,-0.017379,-0.432544,-0.515035,None,None,None,None,-0.382580
1,1926-02-02,0.486124,0.686540,0.577793,0.547870,0.502511,0.492223,None,None,None,None,0.006099
2,1926-02-03,0.446565,0.479530,0.435945,0.754013,0.828716,0.107086,None,None,None,None,-0.339479
3,1926-02-04,0.468391,0.506404,0.393217,0.882955,0.529893,-0.131754,None,None,None,None,-0.600146
4,1926-02-05,-0.026952,-0.292613,0.077437,0.145242,-0.065884,0.756747,None,None,None,None,0.783699
...,...,...,...,...,...,...,...,...,...,...,...,...
25518,2022-12-23,-0.034800,0.396762,0.360643,0.724822,0.633322,-0.970691,None,None,None,None,-0.935892
25519,2022-12-27,-0.176954,-0.097301,-0.272677,-0.140204,-1.027927,-3.185845,None,None,None,None,-3.008891
25520,2022-12-28,-0.115678,-0.968472,-1.298265,-1.221485,-1.431261,-0.389858,None,None,None,None,-0.274179
25521,2022-12-29,0.260518,1.463701,1.852204,1.525173,2.534998,4.734355,None,None,None,None,4.473837
25522,2022-12-30,-0.149793,-0.417972,-0.316293,-0.271487,-0.106797,0.858423,None,None,None,None,1.008216

In [7]:
_ = DailyPortfolios.read_cts_predictor("BidAskSpread", frequency="decile", vw=False)
_ = DailyPortfolios.read_cts_predictor("BidAskSpread", frequency="decile", vw=True)
_ = DailyPortfolios.read_cts_predictor("BidAskSpread", frequency="quintile", vw=False)
_ = DailyPortfolios.read_cts_predictor("BidAskSpread", frequency="quintile", vw=True)
del _

In [8]:
all_predictor_ports = read_predictor_ports_full()
pd.DataFrame(all_predictor_ports)

,signal_name,port,date,ret,signal_lag,n_long,n_short
0,AM,port01,1951-07-31,7.661648,0.681619,67,0
1,AM,port01,1951-08-31,4.273648,0.639816,67,0
2,AM,port01,1951-09-28,1.315270,0.617079,67,0
3,AM,port01,1951-10-31,-3.942980,0.612266,67,0
4,AM,port01,1951-11-30,1.028670,0.637710,67,0
...,...,...,...,...,...,...,...
1183281,zerotradeAlt12,portLS,2022-08-31,-1.467892,NaN,491,492
1183282,zerotradeAlt12,portLS,2022-09-30,4.607782,NaN,490,491
1183283,zerotradeAlt12,portLS,2022-10-31,-5.818550,NaN,492,492
1183284,zerotradeAlt12,portLS,2022-11-30,-2.581228,NaN,491,492
1183285,zerotradeAlt12,portLS,2022-12-30,5.437231,NaN,492,492

In [9]:
values, all_ports = DailyPortfolios.read_predictor(all_predictor_ports[0]["signal_name"], vw=True)
print(all_ports)
pd.DataFrame(values)

('port01', 'port02', 'port03', 'port04', 'port05', 'portLS')

,date,port01,port02,port03,port04,port05,port06,port07,port08,port09,port10,portLS
0,1951-07-02,0.437656,0.751156,0.695964,0.483364,1.055240,None,None,None,None,None,0.617584
1,1951-07-03,0.820599,0.450872,0.730964,0.701926,1.446899,None,None,None,None,None,0.626300
2,1951-07-05,1.592783,1.939588,1.991927,1.007977,2.560996,None,None,None,None,None,0.968213
3,1951-07-06,0.048693,0.082860,-0.352517,-0.007209,0.062074,None,None,None,None,None,0.013380
4,1951-07-09,0.517417,0.223910,0.325406,0.047123,0.075076,None,None,None,None,None,-0.442340
...,...,...,...,...,...,...,...,...,...,...,...,...
18024,2022-12-23,0.177421,0.809064,1.002917,0.938002,0.632599,None,None,None,None,None,0.455179
18025,2022-12-27,-0.918393,-0.071020,0.172570,0.150531,-0.023797,None,None,None,None,None,0.894595
18026,2022-12-28,-1.185585,-1.333443,-1.627837,-1.292865,-0.619723,None,None,None,None,None,0.565863
18027,2022-12-29,2.234841,1.507996,1.489975,1.610972,1.584760,None,None,None,None,None,-0.650081
18028,2022-12-30,-0.290136,-0.096470,-0.225042,-0.206287,-0.154875,None,None,None,None,None,0.135261

In [10]:
pd.DataFrame(FirmLevelCharacteristics.read_individual_predictor("BM"))

         permno  yyyymm     value
0         10000  198704 -2.895161
1         10000  198705 -2.895161
2         10001  198612 -0.104958
3         10001  198701 -0.104958
4         10001  198702 -0.104958
...         ...     ...       ...
2636825   93436  202208 -3.647020
2636826   93436  202209 -3.647020
2636827   93436  202210 -3.647020
2636828   93436  202211 -3.647020
2636829   93436  202212 -3.647020

[2636830 rows x 3 columns]